// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://grjracofmfketvjnbrdz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdyanJhY29mbWZrZXR2am5icmR6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIzMzQ0MjQsImV4cCI6MjA2NzkxMDQyNH0.d3yhE-Nld48UbHjIRwIYlu1c5BaR6uQhuucEjKHXIBo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});